server:
  servlet:
    context-path: "/api"


spring:
  datasource:
    hikari:
      initializationFailTimeout: 20000
      connectionTimeout: 30000
      validation-query: SELECT 1
      validation-timeout: 30000
    tomcat:
      max-wait: 20000
      test-on-borrow: true
      test-while-idle: true
      validation-query: SELECT 1
      validation-query-timeout: 1000
      validation-interval: 1000
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true
    banner-mode: off
  profiles:
    active: local
  sql:
    init:
      continue-on-error: true
